In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import TextVectorization, Embedding, SimpleRNN, Dense
from keras import Sequential
import numpy as np

# Using RNN

In [2]:
text="This is a sample text used to demonstrate predictive text with basic RNNs.In this example,we'll predict the next word as you type "

In [3]:
tokenizer = TextVectorization()
tokenizer.adapt(text.split())

In [4]:
text_sequences = tokenizer(text)
text_sequences

<tf.Tensor: shape=(22,), dtype=int64, numpy=
array([ 2, 16, 21, 11,  3,  7,  9, 18, 13,  3,  6, 19, 12,  2, 17, 14, 10,
       15,  5, 20,  4,  8], dtype=int64)>

In [5]:
x = text_sequences[:-1]
y = text_sequences[1:]

`text_sequences[:-1]` is slicing the list of text sequences to create `x`. It *takes all elements from the beginning of the list to the second-to-last element*. This means it creates x with all sequences except the last one.

`text_sequences[1:]` is slicing the list of text sequences to create `y`. It *takes all elements starting from the second element to the end of the list*. This means it creates y with all sequences except the first one.

In [6]:
model = Sequential([
    Embedding(input_dim=len(tokenizer.get_vocabulary()), output_dim=64, input_length=1),
    SimpleRNN(128,return_sequences=True),
    Dense(len(tokenizer.get_vocabulary()),activation='softmax')
])

In [7]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [8]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 526ms/step - loss: 3.0946
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 3.0805
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 3.0664
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 3.0523
Epoch 5/50
1/1 [==============================] - 0s 2ms/step - loss: 3.0381
Epoch 6/50
1/1 [==============================] - 0s 4ms/step - loss: 3.0240
Epoch 7/50
1/1 [==============================] - 0s 2ms/step - loss: 3.0097
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 2.9953
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 2.9808
Epoch 10/50
1/1 [==============================] - 0s 3ms/step - loss: 2.9660
Epoch 11/50
1/1 [==============================] - 0s 2ms/step - loss: 2.9510
Epoch 12/50
1/1 [==============================] - 0s 2ms/step - loss: 2.9357
Epoch 13/50
1/1 [==============================] - 0s 3ms/step - loss: 

In [9]:
def generate_next_word(seed_text):
  seed_sequence=tokenizer(seed_text)
  predicted_probabilities=model.predict(seed_sequence)
  predicted_index=np.argmax(predicted_probabilities)
  predicted_word=tokenizer.get_vocabulary()[predicted_index]
  return predicted_word

In [10]:
input_text = "used"
predicted_word = generate_next_word(input_text)
print(f"Input: '{input_text}', Predicted: '{predicted_word}'")

1/1 [==============================] - 0s 94ms/step
Input: 'used', Predicted: 'to'


# Using LSTM

In [11]:
from keras.layers import LSTM

In [12]:
text="This is a sample text used to demonstrate predictive text with basic LSTM.In this example,we'll predict the next word as you type "

In [13]:
tokenizer = TextVectorization()
tokenizer.adapt(text.split())

In [14]:
text_sequences = tokenizer(text)
text_sequences

<tf.Tensor: shape=(22,), dtype=int64, numpy=
array([ 2, 16, 21, 11,  3,  7,  9, 18, 12,  3,  6, 19, 15,  2, 17, 13, 10,
       14,  5, 20,  4,  8], dtype=int64)>

In [15]:
x = text_sequences[:-1]
y = text_sequences[1:]

`text_sequences[:-1]` is slicing the list of text sequences to create `x`. It *takes all elements from the beginning of the list to the second-to-last element*. This means it creates x with all sequences except the last one.

`text_sequences[1:]` is slicing the list of text sequences to create `y`. It *takes all elements starting from the second element to the end of the list*. This means it creates y with all sequences except the first one.

In [16]:
model = Sequential([
    Embedding(input_dim=len(tokenizer.get_vocabulary()), output_dim=64, input_length=1),
    LSTM(128,return_sequences=True),
    Dense(len(tokenizer.get_vocabulary()),activation='softmax')
])

In [17]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [18]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 890ms/step - loss: 3.0903
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 3.0875
Epoch 3/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0847
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0818
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 3.0789
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0759
Epoch 7/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0729
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0698
Epoch 9/50
1/1 [==============================] - 0s 6ms/step - loss: 3.0667
Epoch 10/50
1/1 [==============================] - 0s 3ms/step - loss: 3.0635
Epoch 11/50
1/1 [==============================] - 0s 5ms/step - loss: 3.0602
Epoch 12/50
1/1 [==============================] - 0s 4ms/step - loss: 3.0567
Epoch 13/50
1/1 [==============================] - 0s 3ms/step - loss: 

In [19]:
def generate_next_word(seed_text):
  seed_sequence=tokenizer(seed_text)
  predicted_probabilities=model.predict(seed_sequence)
  predicted_index=np.argmax(predicted_probabilities)
  predicted_word=tokenizer.get_vocabulary()[predicted_index]
  return predicted_word

In [20]:
input_text = "this"
predicted_word = generate_next_word(input_text)
print(f"Input: '{input_text}', Predicted: '{predicted_word}'")

1/1 [==============================] - 0s 186ms/step
Input: 'this', Predicted: 'is'
